### ISSUE TITLE
boardAdmin.user.get in not a function when creating a board.

### ISSUE THREAD

**Issue by Temetz** [N4SJAMK/teamboard-client-react#292]
- New user without any boards.
- Create a new board.
- Reload the page.

![image](https://cloud.githubusercontent.com/assets/8721037/8950965/0e1aecde-35d1-11e5-9463-84408fddce70.png)

After the reload when I try to create a new board i get the following error:

```
Error: Board not found! {stack: Error: Board not found!↵
at Object.BOARD_REMOVE (http://sut-cb.n4sjamk.org/dist/app.js:58304:10)↵
at Object.<anonymous> (http://sut-cb.n4sjamk.org/dist/app.js:60509:35)↵
at Object.emit (http://sut-cb.n4sjamk.org/dist/app.js:7723:10)↵
at Object.dispatch (http://sut-cb.n4sjamk.org/dist/app.js:60558:14)↵
at http://sut-cb.n4sjamk.org/dist/app.js:53037:10↵
at run (http://sut-cb.n4sjamk.org/dist/app.js:2027:39)↵
at http://sut-cb.n4sjamk.org/dist/app.js:2038:28↵
at module.exports (http://sut-cb.n4sjamk.org/dist/app.js:580:25)↵
at queue.(anonymous function) (http://sut-cb.n4sjamk.org/dist/app.js:1062:7)↵
at Number.run (http://sut-cb.n4sjamk.org/dist/app.js:1050:5)}
```

Client version  v1.2.119
API version v0.4.42
IMG version v0.1.10

**Comment by Temetz** [comment]
Also seems to happen if I refresh the workspace without any boards present.

**Comment by tanelih** [comment]
Oops :hammer:
